#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

PRIVATE_ENV_FILE="$HOME/.env"

if [ -f "$PRIVATE_ENV_FILE" ]; then
    source "$PRIVATE_ENV_FILE"
else
    echo "Warning: Private environment variables file not found at $PRIVATE_ENV_FILE" >&2
    echo "Please create it with your API keys if needed, and set permissions to 600." >&2
fi

export PATH="${PATH}:${HOME}/.local/bin/"
export PATH=~/.npm-global/bin:${PATH}
export MANPAGER='nvim +Man!'

eval "$(fzf --bash)"

alias ls='ls --hyperlink=auto --color=always'
alias grep='kitten hyperlinked_grep --smart-case "$@" --color=always'
alias ssh='kitten ssh'
alias icat='kitten icat'
alias diff='kitten diff'
alias gitdiff='git difftool --no-symlinks --dir-diff'
alias fed='nvim $(fzf -m)'

PS1='[\u@\h \W]\$ '
(cat ~/.cache/wal/sequences &)
catnap
